title = "Session Technologies"
baseURL = "https://session.it/"
languageCode = "en-us"
theme = "ultimate-hugo"
staticDir = "static"
publishDir = "docs"

[params]

  sections = [
    { slider = "top" }, 
    { simple = "wrapper" },
    { grid = "services" },
    { carousel = "technologies" },
    { form = "contact" }]

  [params.meta]
    author = "Session Technologies"
    description = "Session Technologies - Claim your time back"

  [params.integrations]
    gacode = ""
    jivoid = ""
    privyid = ""
    recapcha = "6LedJ3UUAAAAACNXS56aQzPpDKenasql3Fg9KArG"

  [params.header]
    enable = false
    logo = "img/logo.png"

  [params.footer]
    enable = false