baseURL: https://session.it
languageCode: es
title: Session Technologies
theme: hugo-fresh
publishDir: docs


params:
  jivoid:
  analyticsid:
  logo: /images/logos/sessiontechnologies.png
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    sitename: Session Technologies
    title: Claim your time back
    subtitle: Filling the gap between human challenges and technology
    buttontext: Contact us
    buttonlink: "#contact-us"
    image: illustrations/multitasking.png
  navbar:
  - title: Products
    url: "#products"
  - title: Methodology
    url: "#method"
  - title: Contact us
    url: "#contact-us"
    button: true

  products:
    ancor: products
    title: Our products
    subtitle: Turn-key solutions, first hour is on us
    tiles:
    - title: Process automation package
      icon: mouse-globe
      buttonText: 
      url: "#contacto"
      text: To improve team productivity and streamline activities.
    - title: ChatOps
      icon: plug-cloud
      buttonText: 
      url: "#contacto"
      text: To design, build and deploy chat bots that your customers can use to interact with your systems.
    - title: Open source green light
      icon: plug-cloud
      buttonText: 
      url: "#contacto"
      text: The ultimate validation to consume or contribute to open source projects with peace of mind
  services:
    ancor: method
    title: A new approach to time and technology
    subtitle: Time is the most valuable thing a man can spend.
    features:
    - title: Requirement gathering
      text: Initial requirements investigation and detailed report of activities, deliverables and costs.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Deliverables
      text: Access to preview deliverables at any stage of the project
      icon: doc-sync
    - title: KPIs
      text: Measurement tools and continuous sampling
      icon: mobile-feed
    - title: Education
      text: Documentation and training material (turn-key experience)
      icon: mobile-feed
  technologies:
  - openshift
  - github
  - travisci
  - alfresco
  - googlesuite
  - hubspot
  footer:
    # Logo (from /images/logos/___)
    logo: sessiontechnologies.png
    footerlinks:
    - id: privacy
      linkname: Privacy policy