title = "Session Technologies"
baseURL = "https://session.it"
languageCode = "en-us"
theme = "airspace-hugo"
staticDir = "static"
publishDir = "docs"

[params]
  date_format = "6 January 2006"

  home = "Home"

  [params.topmenu]
    enable = false

  [params.slider]
    enable = true
    title = "Session IT"
    subtitle = "Technologies that save time"
    paragraph = "In a world dominated by globalization and decentralization, digital transformation is key to survive. <b>Session Technologies</b> brings experience and leadership in information technologies that allow to operate faster, smoother and with less human interaction, saving precious time that can be invested elsewhere."

  [params.wrapper]
    enable = true
    title = "5 steps to success"
    italic = "We are a small, efficient and distributed team of professionals, covering a wide set of technologies and platforms and delivering the best solutions for our customers problems."
    paragraph = "With customers in United States, Spain, Italy and the Netherlends, Session Technologies provides an established approach to drive customer success: <b>gather requirements</b>, <b>plan<b>, <b>implement</b>, <b>measure</b> and <b>train</b>."

  [params.blog]
    enable = false

  [params.feature]
    enable = false

  [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"