copyright = "Session Technologies SL"
title = "Session Technologies"
baseURL = "https://session.it/"
theme = "ultimate-hugo"
staticDir = "static"

recapcha = "6LenXYgUAAAAAFt1Y8i4NHvtoXwEFV0sy1nqcpOK"
gacode = ""
jivoid = ""
privyid = ""

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    languageCode = "en-us"
    weight = 1
  [languages.es]
    languageCode = "es"
    weight = 2
