title = "Session Technologies"
baseURL = "https://session.it/"
languageCode = "en-us"
theme = "ultimate-hugo"
staticDir = "static"
publishDir = "docs"

[params]

  logo = "img/logo.png"
  
  gacode = ""
  jivoid = ""
  privyid = ""

  sections = [
    { slider = "top" }, 
    { simple = "wrapper" },
    { grid = "services" },
    { carousel = "technologies" },
    { form = "contact" }]

  [params.header]
    enable = false

  [params.footer]
    enable = false
